# Generated by Django 2.2.4 on 2019-08-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regiao', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='regioes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regiao.Regiao'),
            preserve_default=False,
        ),
    ]
