# Generated by Django 2.2.4 on 2019-08-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190826_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='regioes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regiao.Regiao'),
        ),
    ]
